version: '3.8'

services:
  # mongodb:
  #   image: mongo:latest
  #   env_file:
  #     - ./.env
  #   ports:
  #     - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
  #   volumes:
  #     - ./data:/data/db

  server:
    build: ./server
    env_file:
      - ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - ./server:/app # bind mount volume for development
      - /app/node_modules # anonymous volume
    # depends_on:
    # - mongodb

  nginx:
    build: ./nginx
    hostname: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
