version: '3.8'

services:
  # mongodb:
  #   image: mongo:latest
  #   env_file:
  #     - ./.env
  #   ports:
  #     - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
  #   volumes:
  #     - ./data:/data/db

  server:
    build: ./server
    env_file:
      - ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - ./server:/app/code # bind mount volume to folder inside of /app/code
    # depends_on:
    # - mongodb
